version: "3.8"

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: vektora_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vektora
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
  redis:
    image: redis:7-alpine
    container_name: vektora_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
volumes:
  pgdata:
  redis_data:
